version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - middleware

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www
    environment:
      - DB_HOST=db
      - DB_DATABASE=chat
      - DB_USERNAME=chat_user
      - DB_PASSWORD=secure_password
    depends_on:
      - db

  middleware:
    build: ./middleware
    ports:
      - "3000:3000"
    volumes:
      - ./middleware:/app

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: chat
    volumes:
      - ./db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
